# Burak ERÇIKTI ♦ 20180808082
# Scientific Programming → Exercises(2)

# ۩ 4 → Lists

**► Exercise 4.1 → Sh☻rt questi☻ns◄**

In [10]:
def list_elements(_list):
    print('▀▄List elements▄▀')
    for ele in _list:
        print(ele)
        
def reverse_list(_list):
    print('▄▀Reversed list elements▀▄')
    for ele in reversed(_list):
        print(ele)
        
def len_list(_list):
    index = 0
    print('▀▄Length of list▄▀')
    for ele in _list:
        index += 1
    return index
        
_list = [1,2,3]

list_elements(_list)
reverse_list(_list)
print(len_list(_list))

▀▄List elements▄▀
1
2
3
▄▀Reversed list elements▀▄
3
2
1
▀▄Length of list▄▀
3


**► Exercise 4.2 → C☻pying lists◄**

In [11]:
# (_a)
# In Pyth●n → list is an ●rdered, changeable, duplicates & indexed 
# collection of objects. It stores multiple elements in a single variables.
# A list can store different data types.
a = ['Cobain', 7, True, 5.0 , 7]
print('▌Initial state of list "a"▌')
# List of a
print(a)
print()
# (_b)
# list a copied to b
b = a
print('▌b▌')
print(b)
print()
# (_c)
b[1] = 0
print('▌Changed the 2nd index of b to 0▌')
print(b)
print()
# (_d)
# Since the 2nd element of list b has changed, 
# the 2nd element of list a has changed.
print('▌List a▌')
print(a)
print()
# (_e)
# final state list a copied to c
c = a[:]
print('▌Initial state of list "c"▌')
print(c)
print()
# (_f)
c[2] = False
print('▌Changed the 3nd index of c to False▌')
print(c)
print()
# (_g)
# List a not change.
print('▌Final state of list "a"▌')
print(a)
print()

# bonus
def zero_starting(l):
    l[0] = 0
    return l

# The list change with the function
print('▌First element is 0▌')
l = ['x', 'Hendrix', '13']
print(zero_starting(l))

▌Initial state of list "a"▌
['Cobain', 7, True, 5.0, 7]

▌b▌
['Cobain', 7, True, 5.0, 7]

▌Changed the 2nd index of b to 0▌
['Cobain', 0, True, 5.0, 7]

▌List a▌
['Cobain', 0, True, 5.0, 7]

▌Initial state of list "c"▌
['Cobain', 0, True, 5.0, 7]

▌Changed the 3nd index of c to False▌
['Cobain', 0, False, 5.0, 7]

▌Final state of list "a"▌
['Cobain', 0, True, 5.0, 7]

▌First element is 0▌
[0, 'Hendrix', '13']


**► Exercise 4.3 → Lists ☻f lists◄**

In [12]:
a = [1, 3, 2]
a = [[]] * 3
print(a)

b = [3, 5, 6]
# "_" is a variable in looping
b = [[] for _ in range(3)]
print(b)

if a == b:
    print("\nThere is no difference, a and b give the same output.")
else:
    print("Different each other.")

[[], [], []]
[[], [], []]

There is no difference, a and b give the same output.


**► Exercise 4.4→ Lists ☻f functions◄**

In [13]:
def starting_zero(l, i):
    l[i] = 0
    return l

l = ['B.B.', '90', 'King']
print(starting_zero(l, 1))

['B.B.', 0, 'King']


**► Exercise 4.5 → Primes◄**

In [14]:
def primes_list(n):
    print("Primes up to → {" + str(n) + "}")
    list = []
    for n in range(2, n + 1):
        # n must be greater than 1 coz first prime is 2
        if n < 2:
            break
        else:
            if n > 1:
                for i in range(2, n//2 + 1):
                    if n % i == 0:
                        break 
                else:
                    list.append(n)
    return list

print(primes_list(101))

Primes up to → {101}
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101]


In [15]:
def first_prime(n):
    x = 0
    # I initialized with first prime number
    prime_number = 2
    list = []
    while x < n:
        # I use check point
        is_active = True
        for i in range(2, prime_number//2 + 1):
            if prime_number % i == 0:
                is_active = False
        if is_active == True:
            x += 1
            list.append(prime_number)
            print("♦ " + str(x) + ". prime ♦ ")
            print(list)
        prime_number += 1

first_prime(18)

♦ 1. prime ♦ 
[2]
♦ 2. prime ♦ 
[2, 3]
♦ 3. prime ♦ 
[2, 3, 5]
♦ 4. prime ♦ 
[2, 3, 5, 7]
♦ 5. prime ♦ 
[2, 3, 5, 7, 11]
♦ 6. prime ♦ 
[2, 3, 5, 7, 11, 13]
♦ 7. prime ♦ 
[2, 3, 5, 7, 11, 13, 17]
♦ 8. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19]
♦ 9. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23]
♦ 10. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
♦ 11. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]
♦ 12. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
♦ 13. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41]
♦ 14. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43]
♦ 15. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
♦ 16. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]
♦ 17. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59]
♦ 18. prime ♦ 
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61]


**► Exercise 4.6 → List c●mprehensi●ns◄**

In [16]:
# (_a)

def comprehensions_list(i, j):
    # This comprehensions for nested for loops.
    # Here I can define a as inner loop and b as outer loop.
    _list = [[a, b] for a in range(1, i + 1) for b in range(1, j + 1)]
    # result would be a list of lists
    return _list
print(comprehensions_list(5, 5))

[[1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5]]


In [17]:
# (_b)
# [i,j]
def comprehensions_list(i, j):
     # with i < j
     # Adds only cases where a is less than b to the list.
    _list = [[a, b] for a in range(1, i + 1) for b in range(1, j + 1) if a < b]
    return _list
print(comprehensions_list(8, 8))

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [1, 7], [1, 8], [2, 3], [2, 4], [2, 5], [2, 6], [2, 7], [2, 8], [3, 4], [3, 5], [3, 6], [3, 7], [3, 8], [4, 5], [4, 6], [4, 7], [4, 8], [5, 6], [5, 7], [5, 8], [6, 7], [6, 8], [7, 8]]


In [18]:
# (_c)

from math import sqrt
# Here I applied the prime numbers control code I wrote in Exercise 1
# with the list comprehension method.
def is_prime(n):
    # I wrote my code to control prime numbers that 
    # I wrote in exercises 1 in list comprehension method.
    _list = [i for i in range(2, int(sqrt(n) + 1)) if n > 1 if n % i == 0]
    result = [False if len(_list) > 1 else True]
    return result

def comprehensions_list(i, j):
    # i + j with both i and j prime and i > j.
    # Adds only cases where a is greater than b to the list.
    _list = [[a, b] for a in range(1, i + 1) for b in range(1, j + 1) if is_prime(a) if is_prime(b) if a > b]
    return _list

print(comprehensions_list(11, 11))

[[2, 1], [3, 1], [3, 2], [4, 1], [4, 2], [4, 3], [5, 1], [5, 2], [5, 3], [5, 4], [6, 1], [6, 2], [6, 3], [6, 4], [6, 5], [7, 1], [7, 2], [7, 3], [7, 4], [7, 5], [7, 6], [8, 1], [8, 2], [8, 3], [8, 4], [8, 5], [8, 6], [8, 7], [9, 1], [9, 2], [9, 3], [9, 4], [9, 5], [9, 6], [9, 7], [9, 8], [10, 1], [10, 2], [10, 3], [10, 4], [10, 5], [10, 6], [10, 7], [10, 8], [10, 9], [11, 1], [11, 2], [11, 3], [11, 4], [11, 5], [11, 6], [11, 7], [11, 8], [11, 9], [11, 10]]


In [19]:
# (_d)

# x = 3, i=0, j=2 | i=1, j=4 | i=2, j=6
def arbitrary_poly(x, list):
    # (3 ** 0) * 2 | (3 ** 1) * 4 | (3 ** 2) * 6
     return sum([x ** i * j for i,j in enumerate(list)])

x = 3
list = [2, 4, 6]
print(arbitrary_poly(x, list))

68


**► Exercise 4.7 → Filter◄**

In [20]:
# Median Age by Country
median_age_country = [
    ['japan →', 47.3],
    ['italy', 45.5],
    ['Hollanda', 42.6],
    ['Birleşik Krallık', 40.5],
    ['İzlanda', 36.5],
    ['Turkey', 30.9],
    ['Hindistan', 27.9],
    ['Jamaica', 26],
    ['Irak', 20],
    ['Uganda', 15.8]]

def myfilter(function, ite):
    return [i for i in median_age_country if function(i)]

print("◙ Under 30 years old with myfilter() ◙")
print(myfilter(lambda l: l[1] < 30, median_age_country))
print()

# I used lambda expression because
# it is a function definition that takes arguments.
# age_list will contain countries with a Median Age greater than 30.
age_list = filter(lambda l: l[1] > 30, median_age_country)
print("◙ Over 30 years old with filter() ◙")
print(dict(age_list))

◙ Under 30 years old with myfilter() ◙
[['Hindistan', 27.9], ['Jamaica', 26], ['Irak', 20], ['Uganda', 15.8]]

◙ Over 30 years old with filter() ◙
{'japan →': 47.3, 'italy': 45.5, 'Hollanda': 42.6, 'Birleşik Krallık': 40.5, 'İzlanda': 36.5, 'Turkey': 30.9}


**► Exercise 4.8 → Flatten a list ●f lists◄**

In [21]:
def flatten_list(sub_list):
    combine = [b for a in sub_list for b in a ]
    return combine

sub_list = [[1, 3], [3, 6], [7, 8]]
print(flatten_list(sub_list))


[1, 3, 3, 6, 7, 8]


**► Exercise 4.9 → Finding the l☻ngest w☻rd◄**

In [22]:
def giraffe_word(_txt):
    # split() splits a string into a list.
    _words = _txt.split()
    # len() helps me find the maximum.
    longest_str = len(max(_words, key = len))
    # iterate word by word
    _list = [i for i in _words if len(i) >= longest_str]
    # if there is more than one longest word, I print the last long word.
    final = [_list[1:] if len(_list) > 1 else _list]
    # If I want to list more than one long word, I just return "_list".
    return final
         
txt = 'Hello, how was the football match earlier today???'
print(giraffe_word(txt))

[['today???']]


**► Exercise 4.10 → C●llatz sequence◄**

In [23]:
def collatz_sequence(n):
    list = []
    list.append(n)
    while n != 1:
        if n % 2 == 0:
            # If the # even, n ÷ 2
            n = int(n / 2)
        else:
            # If the # odd, triple it and add 1.
            n = 3 * n + 1
        list.append(n)
    return list


def find_longest_collatz(x):
    longest_collatz = 0
    result = 0
    for i in range(1, x):
        length = len(collatz_sequence(i))
        if length > longest_collatz:
            longest_collatz = length
            result = i
    return 'The integer leading to the longest collatz sequence is ◙ ' + str(result)

print(collatz_sequence(5))
print(find_longest_collatz(5))
print(collatz_sequence(3))


[5, 16, 8, 4, 2, 1]
The integer leading to the longest collatz sequence is ◙ 3
[3, 10, 5, 16, 8, 4, 2, 1]


**► Exercise 4.11 → Piv●ts◄**

In [24]:
# function has a value x and a list ys
def combine_sort(x, ys):
    # Initially, I sort the list in ascending order with the .sort()s method.
    ys.sort()
    for y in ys:
        if x <= y:
            # element x and then the rest of the values in ys
            ys.insert(ys.index(y), x)
            break
    print("pivot is ♣ " + str(x))
    # returns a list that contains the value x and all elements of ys  
    return ys

print(combine_sort(314, [170, 703, 313, 640]))

pivot is ♣ 314
[170, 313, 314, 640, 703]


**► Exercise 4.12 → Prime challenge◄**

In [25]:
def prime_expert(n):
    
    # len() returns the # of items.
    is_prime = lambda n: len([i for i in range(2, n//2 + 1) if n % i == 0]) == 0
    return [i for i in range(2, n + 1) if is_prime(i)]

print(prime_expert(101))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101]


# ۩ 5 → Tuples

**► Exercise 5.1 → Swapping tw● values◄**

In [26]:
a, b = '2', 'U' # The use of commas means that the tuple object has been created.
a, b = b, a # one line swap
print(a, b)

U 2


**► Exercise 5.2 → Zip◄**

In [1]:
# The zip() function sequentially combines the elements in the iterator. 
# So it concatenates two tuples
def _zip(list_x, list_y):
    zip_list = list(zip(list_x, list_y))
    return zip_list

def un_zip(final_zip):
    # (Asterisk*) When we type *final_zip, all bundles in final_zip 
    # are applied as separate arguments to the zip() function
    # I took advantage of list comprehension
    return [list(l) for l in zip(*final_zip)]

a = [(1, 3), (5, 7)]
b = [(0, 2), (4, 6)]
print(_zip(a, b))
# [[(1, 3), (5, 7)], [(0, 2), (4, 6)]]
print(un_zip(_zip(a, b)))

[((1, 3), (0, 2)), ((5, 7), (4, 6))]
[[(1, 3), (5, 7)], [(0, 2), (4, 6)]]


**► Exercise 5.3 → Distance◄**

In [1]:
import math
import numpy as np
# I found the shortest distance between two points
# of any size using euclidean distance.
def distance(x, y):
    # It is the square root of the sum of
    # the squares of the difference between two points.
    _dist = math.sqrt(sum([(x[i] - y[i])**2 for i in range(len(x))]))
    return _dist

x = np.array([5,6,7])
y = np.array([8,9,9])
print('l1 and l2 distances between x and y is →', distance(x, y))

l1 and l2 distances between x and y is → 4.69041575982343


# ۩ 6 → Dicti●naries

**► Exercise 6.1 → Printin a dicti♦nary◄**

In [28]:
def mydic(dic):
    # # I used items() func to be able to return key/value pairs
    for key, val in dic.items():
        print(key, val)

mydic({
    'name': 'James Harden',
    'age': 32,
    'weight - height': ['196', '100'],
    'is active player?': True,
    'team': 'Philadelphia 76ers'  
})

name James Harden
age 32
weight - height ['196', '100']
is active player? True
team Philadelphia 76ers


**► Exercise 6.2 → Hist♦gram◄**

In [29]:
import collections

def histogram(list):
    dic = {}
    for ele in list:
        if ele in dic:
            dic[ele] += 1
        else:
            dic[ele] = 1
    return dic

print(histogram([
    'L', 'k', 'J',
    7, 3.14, 7, True, 
    False, True, 'k', 'J'  
]))

# The counter() function returns the number of 
# elements in iterable (list, tuple e.g) objects.
print()
print(collections.Counter([
    'L', 'k', 'J',
    7, 3.14, 7, True, 
    False, True, 'k', 'J'  
]))


# I can use a counter but if the queries contain keys that may not be 
# in the dict, I can have the Counter query the dict in a method and run it.
def counter(list):
    counter = collections.Counter()
    for ele in list:
            counter[ele] += 1
    return counter
print()
print(counter([
    'L', 'k', 'J',
    7, 3.14, 7, True, 
    False, True, 'k', 'J'  
]))



{'L': 1, 'k': 2, 'J': 2, 7: 2, 3.14: 1, True: 2, False: 1}

Counter({'k': 2, 'J': 2, 7: 2, True: 2, 'L': 1, 3.14: 1, False: 1})

Counter({'k': 2, 'J': 2, 7: 2, True: 2, 'L': 1, 3.14: 1, False: 1})


**► Exercise 6.3 → Get meth♦d◄**

In [30]:
def get_method(list):
    dic = {}
    for ele in list:
        # If the key is in the dictionary
        if ele in dic:
            # get() have key and default value
            # returns value
            dic[ele] = dic.get(ele, 0) + 1        
        else:
            # returns default value 
            dic[ele] = 1
    return dic

mydic_list = {
    'name': 'James Harden',
    'age →': 32,
    'weight_height': ['196', '100'],
    'is_active_player?': True,
    'team': 'Philadelphia_76ers'  
}


print(get_method([
    'L', 'k', 'J',
    7, 3.14, 7, True, 'L',
    False, True, 'k', 'J'
]))

print()
# I created a dictionary called mydic_list, if the value has a key
# return the value of the keyword with the help of get().
print(mydic_list.get('name'))

{'L': 2, 'k': 2, 'J': 2, 7: 2, 3.14: 1, True: 2, False: 1}

James Harden


**► Exercise 6.4 → Random text generat♦r◄**

In [31]:
def process_line(line):
    word_list = []
    _words = line.split(" ")
    # Begın → the → fire → and → the → wind. → END
    # [('BEGIN', 'in')]
    _words.insert(0, 'BEGIN')
    #('night', 'END')]
    _words.append('END')

    len_words = len(_words) - 1
    for i in range(len_words):
        word_list.append((_words[i], _words[i + 1]))
    return word_list


txt = "the fire and the wind."
print(process_line(txt))

[('BEGIN', 'the'), ('the', 'fire'), ('fire', 'and'), ('and', 'the'), ('the', 'wind.'), ('wind.', 'END')]


**► Exercise 6.5 → Vect◘r functions◄**

In [32]:
# (_a)

import numpy as np

def add_vectors(v1, v2):
    if (len(v1) == len(v2)):
        # if dimensions equal, two vectors add
        coord = v1 + v2
        print(coord)  
    else:     
        print('not equal dimensions')
# .array represent vectors
v1 = np.array([[3, 3],[5, 7]])
v2 = np.array([[7, 5],[3, 2]])

add_vectors(v1, v2)

[[10  8]
 [ 8  9]]


In [33]:
# (_b)

import numpy as np

def inproduct(v1, v2):
    a = np.array(v1)
    b = np.array(v2)
    # I can also use the .dot() function here, but it often doesn't 
    # give the same result. I got the result of .inner() function
    # faster than dot in terms of performance.
    product = np.inner(a, b)
    print(product)

v1 = [1, 4]
v2 = [11, 14]
# 1•11 + 4•14 = 67
inproduct(v1, v2)

67


In [34]:
# (_c)

import numpy as np
from scipy import sparse

# Storing sparse vectors in a two-dimensional vector data structure 
# causes performance loss. Instead, we can use the .csr_matrix() method
# to transform dense and sparse vectors.
def add_sparse(v1, v2):
    sa = sparse.csr_matrix(np.array(v1))
    sb = sparse.csr_matrix(np.array(v2))
    sc = sa + sb
    print(sc)
    
print('Vector A')
A = np.array([[1,0,0],[1,0,3]])
print((A))
print('Vector B')
B = np.array([[1,2,0],[0,0,4]])
print((B))
print()
print('two sparse vectors add')
add_sparse(A, B)

Vector A
[[1 0 0]
 [1 0 3]]
Vector B
[[1 2 0]
 [0 0 4]]

two sparse vectors add
  (0, 0)	2
  (0, 1)	2
  (1, 0)	1
  (1, 2)	7


In [35]:
# (_d)

import numpy as np
from scipy import sparse

def multiplies_sparse(v1, v2):
    # I can use .multiply() method to do multiplication(Product of two sparse vectors)
    multiplies = sparse.csr_matrix(v1).multiply(sparse.csr_matrix(v2)).todense()
    print(multiplies)

a = np.array([[0, 0, 1],[2, 0, 0],[0, 1, 3]])
b = np.array([2, 1, 5])

print(a, '  ', b)
print()
print('▼ Product of two sparse vectors ▼')
multiplies_sparse(a, b)

[[0 0 1]
 [2 0 0]
 [0 1 3]]    [2 1 5]

▼ Product of two sparse vectors ▼
[[ 0  0  5]
 [ 4  0  0]
 [ 0  1 15]]


In [36]:
# (_e)

import numpy as np
from scipy import sparse


def add_dense_sparse(v1, v2):
    dense_v1 = np.array(v1)
    print(dense_v1)
    print()
    sparse_v2 = sparse.csr_matrix(np.array(v2))
    print(sparse_v2)
    print()
    add = dense_v1 + sparse_v2
    return add


v1 = [[3, 3],[5, 7]]
v2 = [[7, 5],[3, 2]]
print('▼ Add of sparse and dense vectors ▼')
print(add_dense_sparse(v1, v2))

▼ Add of sparse and dense vectors ▼
[[3 3]
 [5 7]]

  (0, 0)	7
  (0, 1)	5
  (1, 0)	3
  (1, 1)	2

[[10  8]
 [ 8  9]]


In [37]:
# (_f)

import numpy as np
from scipy import sparse


def multiplies_dense_sparse(v1, v2):
    dense_v1 = np.array(v1)
    print(dense_v1)
    print()
    sparse_v2 = sparse.csr_matrix(np.array(v2))
    print(sparse_v2)
    print()
    multiplies = sparse.csr_matrix.dot(dense_v1, sparse_v2.todense())
    return multiplies


v1 = [[2, 5], [6, 1]]
v2 = [[1, 9], [1, 7]]
print('▼ Product of sparse and dense vectors ▼\n', multiplies_dense_sparse(v1, v2))

[[2 5]
 [6 1]]

  (0, 0)	1
  (0, 1)	9
  (1, 0)	1
  (1, 1)	7

▼ Product of sparse and dense vectors ▼
 [[ 7 53]
 [ 7 61]]


**► Exercise 6.6 → Reverse l♦♦k-up◄**

In [38]:
# I assigned a variable named dic(dictionary) 
# and val inside the function.
def with_value(dic, input):
    # Then I looped the list of (key, value) pairs 
    # for a given dictionary using the .items() method.
    # .items() takes no parameters.
    for k, v in dic.items():
        # I would return k(key) 
        # if v (value) equals the value given in the input.
        if v == input:
            print(k)
    
age_list = {
    'Kurt Cobain': 27,
    'James Hetfield': 59,
    'Yavuz Çetin': 31,
    'Janis Joplin': 27,
    'Kobe Bryant': 42,
    'Amy Winehouse': 27,
    'Diego Maradona': 60,
    'Jimi Hendrix': 27
}
            
with_value(age_list, 27)

Kurt Cobain
Janis Joplin
Amy Winehouse
Jimi Hendrix
